### ISSUE TITLE
[Front] Categoria Exames complementares

### ISSUE THREAD

**Issue by sluisTW** [EscolaDeSaudePublica/registrocovid-front#11]
# Contexto
Esse formulário deve permitir que se salve mais de um registro para os Exames complementares, uma vez que o paciente pode ter mais de um exame realizado ao longo do período de internação. Também pode ocorrer de o paciente ter apenas a ocorrência de um dos exames , de forme que nem todos os campos serão preenchidos para um mesmo paciente.

**Os campos presentes neste formulário seguem abaixo:**
- Data TC tórax (% de opacidade) - **Obrigatório**
- Resultado TC tórax (% de opacidade) - varchar - **Obrigatório**
<br/>

- Data ECG - **Obrigatório**
- Resultado ECG - varchar - **Obrigatório**

# Dentro de escopo
- Criar formulário de "Exames complementares" conforme [Figma](https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID?node-id=682%3A2)
- Cada formulário deve estar vinculado ao paciente em específico.
- Exibir dados previamente cadastrados na própria página.
- Mesmo depois de salvo, novas ocorrências podem ser adicionadas (cada nova ocorrência é um novo registro no BD).
- Fazer redirecionamento para as páginas do menu superior.
- Exibir no topo superior direito a **data de cadastro** e o **número de prontuário** do paciente.
- Após salvo os exames, exibir em ordem crescente de data.

# Fora de escopo
- Edição de campos previamente salvos pelo coletador

# Critérios de Aceite

- [x] **1. Incluir nova ocorrência - durante o preenchimento**
**Dado** que inclui uma nova ocorrência de "Exames complementares"
**Quando** clicar no botão "ADICIONAR OCORRÊNCIA"
**Então** o campo para preenchimento da nova ocorrência será exibido abaixo do cabeçalho
**E** a ocorrência preenchida anteriormente ficará abaixo da nova ocorrência. 

- [x] **2.Excluir uma ocorrência**
**Dado** que eu incluí uma nova ocorrência e **ainda não salvei os dados**
**Quando** clicar no ícone para excluir o exame
**Então** a caixinha do exame será excluída

- [x]  **3. Salvar "Exames complementares"" com sucesso**
**Dado** que eu esteja na pagina de "Exames complementares" de um paciente
**Quando** salvar a página, informando os dados corretamente
**Então** o sistema exibe a mensagem "Dados salvos com sucesso" por 5 segundos 
**E** exibe as complicações salvas **recolhidos** na própria página
**E** não permite excluir informações salvas

- [x] **4. Expandir ítens previamente cadastrados**
**Dado** que eu estou na página de "Exames complementares" com dados previamente cadastrados
**Quando** clicar em um exame (que estará recolhido)
**Então** o campo com o as informações do exame serão expandidas

- [x] **5. Validações nos campos obrigatórios**
**Dado** que eu NÃO preencha completamente os campos obrigatórios durante o preenchimento
**Quando** tentar salvar
**Então** o campo faltante ficará destacado
**E**  aparecerá mensagem em vermelho abaixo do campo

- [x] **6. Acessar página "Exames complementares"**
**Dado** que eu esteja na página de Categorias
**Quando** clicar na opção "Exames complementares"
**Então** devo ser direcionado para a página

**Comment by Edely** [comment]
Gente, para rolar o code review é preciso abrir o pull request.
