### ISSUE TITLE
Verificar Bug na página Exames Complementares - Ambiente Produção

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-front#130]
## Contexto
Bug na página **Exames complementares** - no ambiente de produção. 
- Verificar e corrigir o bug.

- Feedback da usuária Thalyta Carvalho:
  - Ao tentar salvar o resultado do eletrocardiograma que possui texto extenso, apresenta o bug:"ALGO DE ERRADO ACONTECEU"  e não salva.
  - Ao salvar eletrocardiograma, o sistema salvou 3 vezes, por favor, excluir os itens repetidos. 

## Dentro do Escopo

- [x] Verificar porque estava dando erro "ALGO DE ERRADO ACONTECEU" e porque não estava salvando.
- [x] Verificar porque a usuária conseguiu salvar 3x
- [x] Verificar com a Camila a exclusão dos ítens repetidos.

**Comment by ericsonmoreira** [comment]
## Erros encontrados

### Verificar porque estava dando erro "ALGO DE ERRADO ACONTECEU" e porque não estava salvando

O que acontece aqui é: 
1. No banco de dados, o campo **resultado** da tabela **exames_complementares** está como um VARCHAR de 100 caracteres. 
2. Quando se tenta salvar algum **exame_complementar** com **resultado** com mais de 100 caracteres, é disparado um erro no backend referente a esse limite: _"campo examescomplementares.0.resultado não pode ser superior a 191 caracteres"_.

### Verificar porque a usuária conseguiu salvar 3x

Não sei responder. Precisamos de mais informações do fluxo que a coletadora fez.

**Comment by camilaccolares** [comment]
Entradas excedentes excluídas (paciente 126).
