### ISSUE TITLE
[Front] Ajustar rota para categoria hemodiálise

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-front#143]
## Contexto
A rota da Categoria de Hemodiálise é  _/categorias/tratamento-suporte/_, uma vez que a categoria Hemodiálise era denominada Tratamento de suporte. Porém, houve a mudança na nomenclatura da Categoria e não ajustamos a nomenclatura na rota.

## Dentro do escopo
- Ajustar rota para _/categorias/hemodialise/_
- Ajustar no código do projeto, os nomes dos arquivos referentes a essa categoria (tudo que faz menção à Tratamento de Suporte)

**Comment by paulasilvatw** [comment]
DeskCheck realizado com o Varela. A pasta 'Support treatment foi atualizada para "Hemodiálise". Checar a rota quando forem aplicar em produção. Nova rota: /categorias/hemodialise/
