### ISSUE TITLE
[Front] Bug na página Comorbidades - Ambiente de Produção

### ISSUE THREAD

**Issue by luannaalves** [EscolaDeSaudePublica/registrocovid-front#178]
### Contexto
No ambiente de produção, foi constatado que ao tentar salvar outras doenças que o paciente apresenta, e não tendo selecionado umas das cinco opções de doenças do campo Selecione as doenças que o paciente apresenta, o botão Salvar fica desabilitado, impedindo o salvamento.
E ao selecionar uma desta cinco doenças, o botão salvar fica habilitado, porém surge a seguinte mensagem de erro (toast): **Ocorreu um erro ao salvar os dados, por favor tente novamente.**

### Escopo
Na página, comorbidades, verificar o bug que está ocorrendo no salvamento das informações. É necessário que a página permita salvar, mediante qualquer opção de doença que seja selecionada, e ainda mediante campos não preenchidos.

### Critério de Aceite
- [x] Página comorbidades permite salvamento mediante qualquer preenchimento de campo

**Comment by ericsonmoreira** [comment]
@luannaalves Pede para os **coletadores** darem mais informações de quando esse _bug_ acontece. Uma **sequência de passos**, se possível.
