### ISSUE TITLE
[Front] Bug botão salvar página História Pessoal - Ambiente de Produção

### ISSUE THREAD

**Issue by luannaalves** [EscolaDeSaudePublica/registrocovid-front#187]
### Contexto
Na página História Pessoal, o botão salvar está constantemente desabilitado, mesmo ao inserir uma nova informação, este segue desabilitado, impedindo assim a continuidade do trabalho nesta página.

### Escopo
Corrigir bug identificado no ambiente de produção, referente ao **botão Salvar.** Este deve estar habilitado para que os coletadores possam salvar as informações inseridas nesta página.

### Critério de Aceite
- [x] Habilitar botão Salvar, para salvamento de informações na página História Pessoal

**Comment by ericsonmoreira** [comment]
Devido a uma mudança no **backend** (antes quando um paciente não tinha nada salvo sobre sua história pessoal, o retorno era vazio, agora voltam algumas informações, mesmo assim), tive que fazer uma pequena mudança na lógica. Vou commitar diretamente na _develop_.
