### ISSUE TITLE
[Front] Bug no envio de informações salvas para o front - página Exame Físico - Ambiente de Produção

### ISSUE THREAD

**Issue by luannaalves** [EscolaDeSaudePublica/registrocovid-front#189]
### Contexto
Na página Exame físico (admissão e evolução diária), foi identificado pelo Ambiente de Produção que está ocorrendo um bug no envio de informações já salvas para o frontend. Ao adicionar informações referente a uma determinada evolução diária e após salvar, estas informações são enviadas para o backend (conferido pela Camila), porém nenhuma informação é apresentada no front, o que está ocasionando dificuldades para os coletadores continuarem suas atividades.

### Escopo
Identificar o que está ocasionando o bug no backend, referente ao envio para o front de informação já salvas, na página Exame físico (admissão e evolução diária).

O**bs.: já verificado que a correção deverá ser feita no frontend, ver comentário abaixo.**

### Critérios de Aceite
- [x] Enviar informações salvas para o Front, página Exame físico (admissão e evolução diária)

**Comment by ericsonmoreira** [comment]
Realmente, o erro é esse que o @FelipeSVidal falou. Já **commitei** diretamente na **develop**. Por gentileza @camilaccolares, faz o deploy e confirma se era isso mesmo que era pra ser feito.
