### ISSUE TITLE
Login - Front

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-front#2]
# Descrição

*Como* coletador
*Quero* entrar no aplicativo do Registro
*Para que* eu possa preencher os dados dos pacientes com COVID

# Contexto
É necessário uma página na qual o coletador possa se logar com segurança e entrar no aplicativo do Registro Covid. Apenas coletadores registrados podem se logar;
O usuário e a senha devem ser previamente adicionados ao banco de dados; 
O usuário é o número de CPF.

# Dentro de escopo
- Página de login ( campos de usuário e senha);
- Validação dupla dos campos de usuário e senha - retornar mensagem após a validação dos dois campos em caso de erro: "Usuário ou senha incorretos, tente novamente";
- Criar e armazenar a informação do usuário/sessão do coletador logado (a sessão é válida por x tempo);
- O botão de Login só vai ficar disponível após o coletador preencher os dois campos;
- Criptografia da senha (JWT - Json Web Token)

# Fora de escopo
- Criação de senha;
- Recuperação de senha;
- Funcionalidade de registro de usuário;
- Validação do CPF do usuário.

# Critério de aceite

1. Login bem sucedido 
Dado que o coletador inseriu seu usuário e senha
Quando ele clica no botão de login
Então ele será direcionado para a página "Meus pacientes"

2. Login mal sucedido
Dado que o coletador inseriu seu usuário e senha (e algum deles for inválido)
Quando ele clica no botão de login
Então o login não será efetivado
E será exibida a mensagem: "Usuário ou senha incorretos, tente novamente".

3. Usuário não preenche  algum dos campos
Dado que o coletador inseriu apenas usuário ou senha
Quando ele tentar finalizar o login
Então o botão estará desabilitado.

# Protótipo
- AC 1 https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID-WIREFRAME?node-id=3%3A7
- AC 2 https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID-WIREFRAME?node-id=54%3A498
- AC 3 https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID-WIREFRAME?node-id=40%3A128

**Comment by camilaccolares** [comment]
- Penso que a sessão pode ficar ativa por 4-5 horas. Tempo suficiente para um turno de coleta. 

- Não sei se convém incluir a complexidade de validação do CPF agora. A ideia central dessa validação é impedir que sejam cadastrados CPFs incorretos. Partindo do princípio que os CPFs já estarão cadastrados, não faz muito sentido validar. Penso que a funcionalidade será necessária quando formos implementar o cadastro de usuário (no ambiente de gestão).

**Comment by felip-carvalho** [comment]
Então no caso os coletadores serão cadastrados previamente na base de dados e será necessário somente efetuar o login no sistema? Se sim, como ficará em relação a senha de cada usuário?

**Comment by navawho** [comment]
Acho que o coletador pode ter a liberdade de alterar a sua senha pelo sistema

**Comment by giordanasousa** [comment]
Oi pessoal, inicialmente a senha será adicionada diretamente no BD
