### ISSUE TITLE
[Front] Configurar ambiente de homologação

### ISSUE THREAD

**Issue by sluisTW** [EscolaDeSaudePublica/registrocovid-front#21]

**Comment by ferfabricio** [comment]
Solução entregue no PR: https://github.com/EscolaDeSaudePublica/registrocovid-front/pull/35

@jacsonp  @victorMagalhaesPacheco ainda precisará configurar a variável de ambiente: **REACT_APP_API_BASE_URL** com a URL do ambiente de homologação da API.

**Comment by vicmagpac** [comment]
Card bloqueado devido ao processo de migração do serviço DigitalOcean.
