### ISSUE TITLE
Página Meus Pacientes - Front

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-front#3]
# Descrição

*Como* coletador
*Quero* visualizar e encontrar meus pacientes
*Para que* eu possa verificar e/ ou acrescentar informações em seu prontuário.

# Contexto
- Criar uma página onde o coletador possa visualizar a listagem dos seus pacientes cadastrados, e realizar um filtro nos pacientes através do **número de prontuário**;
- Atualmente o único filtro será por número de prontuário de paciente (ID do paciente);
- Todos os pacientes cadastrados pelo coletador irão aparecer nesta página, em ordem decrescente pela data de cadastro (o mais recente primeiro / os mais antigos por último);
- Apenas os pacientes do coletador logado devem aparecer para ele;
- As informações do paciente que serão disponibilizadas nesta página serão: 
  - Número prontuário;
  - Data internação;
  - Data do cadastro (esta data deve ser coletada automaticamente pelo sistema, quando um paciente é inserido)

# Dentro de escopo
- Filtro de busca por número de prontuário (ID paciente)
- Mostrar dados em ordem decrescente: número do prontuário do paciente, data de internação e data de cadastro do paciente.

# Fora de escopo
- Editar informações do paciente
- Remover paciente

# Critério de aceite
1. Visualizar listagem de pacientes
Dado que o coletador está na página Meus Pacientes
Quando ele faz scroll down na página
Então ele pode navegar na lista de pacientes, distribuídos em ordem decrescente pela data de cadastro.

2. Filtrar paciente
Dado que o coletador quer encontrar um paciente específico na página Meus Pacientes
Quando ele filtra pelo número de prontuário
Então a lista dos pacientes vai sendo atualizada a medida que o campo de busca vai sendo preenchido.

# Protótipos
- AC 1 
- AC 2 
https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID?node-id=299%3A195
# Dúvida

**Comment by camilaccolares** [comment]
Acho que AC3 pode ser da história "Visualizar/Editar dados de um paciente"

**Comment by ericsonmoreira** [comment]
## Dúvida

No **critério de aceite 1** em _(...) distribuídos em ordem decrescente pela data de cadastro (...)_, o que é seria melhor: a lista de pacientes já vir ordenada do **Backend** ou ser ordenada no **Frontend**?

**Comment by giordanasousa** [comment]
Tirar a seta da primeira linha (cabeçalho)
