### ISSUE TITLE
[Bug homologação] Ajustes página "Comorbidades / condições clínicas"

### ISSUE THREAD

**Issue by giordanasousa** [EscolaDeSaudePublica/registrocovid-front#84]
## Contexto
- Ajustar campos:
  - **"Outras Condições"** - está permitindo adicionar campos vazios
  - **"Medicações de uso Continuo"** - está permitindo adicionar campos vazios
  - **"Acrescente outras doenças que o paciente apresenta"** - permite adicionar um formulário, porém, sem nenhuma informação; permite excluir o formulário após os dados terem sido salvos.

- Verificar o motivo de não estar trazendo as doenças dentro dos formulários e ajustar. Deve estar igual ao [figma](https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID?node-id=355%3A491)

* Card original: [Front] Categoria Comorbidades / Condições clínicas #7 

## Dentro Escopo:

- [x] **Campo Outras Condições:**
- Fazer verificação antes de adicionar - se o campo estiver vazio, não deve permitir adicionar (coletador clica e nada deve acontecer).

- [x] **Medicações de uso Continuo:**
- Fazer verificação antes de adicionar - se o campo estiver vazio, não deve permitir adicionar (coletador clica e nada deve acontecer).

- [x] **"Acrescente outras doenças que o paciente apresenta":**
  - [x] Campo de adicionar só pode estar habilitado quando o coletador selecionar uma doença.
  - [x] Após a doença ser salva, o botão de excluir o card deve desaparecer.

- [x] Verificar se os formulários de doenças estão buscando todos os campos. Deve ficar igual ao [figma](https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID?node-id=355%3A491)

**Comment by ericsonmoreira** [comment]
Sobre **Verificar se os formulários de doenças estão buscando todos os campos**, estou vendo aqui que o backend está retornando poucas doenças. 

Esse é o retorno da tora _/api/doencas_:

```json
[
  {
    "id": 1,
    "tipo_doenca_id": 1,
    "descricao": "Doença arterial coronariana"
  },
  {
    "id": 2,
    "tipo_doenca_id": 1,
    "descricao": "Insuficiência cardíaca congestiva"
  },
  {
    "id": 3,
    "tipo_doenca_id": 1,
    "descricao": "Arritmia cardíaca"
  },
  {
    "id": 4,
    "tipo_doenca_id": 1,
    "descricao": "Cardiopatia não-especificada"
  },
  {
    "id": 5,
    "tipo_doenca_id": 2,
    "descricao": "Insuficiencia venosa"
  },
  {
    "id": 7,
    "tipo_doenca_id": 3,
    "descricao": "Doença pulmonar obstrutiva crônica"
  },
  {
    "id": 8,
    "tipo_doenca_id": 3,
    "descricao": "Asma"
  }
]
```
Só existem 7 doenças cadastradas sendo retornadas do _backend_. **Tá certo isso Arnaldo?**

**Comment by ericsonmoreira** [comment]
Olhando o código do backend encontrei isso: 
```php
<?php

use Illuminate\Database\Seeder;

class DoencasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('doencas')->insert(['id' => 1,'tipo_doenca_id' => 1,'descricao' => 'Doença arterial coronariana']);
        DB::table('doencas')->insert(['id' => 2,'tipo_doenca_id' => 1,'descricao' => 'Insuficiência cardíaca congestiva']);
        DB::table('doencas')->insert(['id' => 3,'tipo_doenca_id' => 1,'descricao' => 'Arritmia cardíaca']);
        DB::table('doencas')->insert(['id' => 4,'tipo_doenca_id' => 1,'descricao' => 'Cardiopatia não-especificada']);
        DB::table('doencas')->insert(['id' => 5,'tipo_doenca_id' => 2,'descricao' => 'Insuficiencia venosa']);
        DB::table('doencas')->insert(['id' => 7,'tipo_doenca_id' => 3,'descricao' => 'Doença pulmonar obstrutiva crônica']);
        DB::table('doencas')->insert(['id' => 8,'tipo_doenca_id' => 3,'descricao' => 'Asma']);
    }
}
```

Ta faltando coisa...

**Comment by camilaccolares** [comment]
Tá faltando, sim. Só olhar o modelo de dados pra ver os seeds. ;)
